# Use root/example as user/password credentials
version: '3.3'

services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=madero123
      - MYSQL_DATABASE=test
    ports:
      - 3306:3306
    expose:
      - 3306
    networks:
      - backend

networks:
  backend:



